name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull brazf/back-todo:latest
    - name: Delete Old docker container
      run: sudo docker rm -f back-todo-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3001:3001 --name back-todo-container brazf/back-todo
