name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull brazf/back-todo:latest
    - name: Delete Old docker container
      run: sudo docker rm -f back-todo-container || true
    - name: Run Docker Container
      run: sudo docker run -it -p 3003:3000 -e DATABASE_URL="mysql://root:todo92258823823@34.122.31.82:3306/todo" back-todo
