name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build -t back-todo:latest .
    - name: Test docker image
      run: docker run back-todo:latest npm test
    - name: Tag the Docker image
      run: docker tag back-todo:latest brazf/back-todo:latest
    - name: Push to Dockerhub
      run: docker push brazf/back-todo:latest
      
